### ISSUE TITLE
Crash into the HardFault_Handler. -Time got lost

### ISSUE THREAD

**Issue by raf-iggy** [raf-iggy/hot-water-circ#1]
First time at this but.... got got a few grey hairs..
I was exploring how to set localtime  on the Feather M0 Express when everything crashed.

"You are running in safe mode which means something unanticipated happened.
Looks like our core CircuitPython code crashed hard. Whoops!
Please file an issue at https://github.com/adafruit/circuitpython/issues
 with the contents of your CIRCUITPY drive and this message:  - in subject line

**Comment by raf-iggy** [comment]
Today runing the same code that crashed, I got the following error.
main.py output:
Traceback (most recent call last):
  File "main.py", line 8, in <module>
  File "adafruit_pcf8523.py", line 66, in <module>
MemoryError: memory allocation failed, allocating 382 bytes

Investigating further.
